version: '3.8'

services:
  qemu-avr32:
    container_name: "qemu-avr32"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - avr32:/jcstudy
    stdin_open: true
    tty: true
    privileged: true
volumes:
  avr32:
    external: true
