version: '3.8'

services:
  qemu:
    container_name: "qemu"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - qemu-volume:/jcstudy
    stdin_open: true
    tty: true

volumes:
  qemu-volume:
    external: true
